### ISSUE TITLE
generatedDefinitions 

### ISSUE THREAD

**Issue by gpcr** [PharmGKB/cpic-data#1]
What are requirements to generate definitions file ?

For example: "[CYP2D6 Cytochrome P450 Nomenclature DB Haplotype Set](https://www.pharmgkb.org/haplotypeSet/PA165980499)" 

How to generate a definition file  using allele translation table?

https://www.pharmgkb.org/download.do?objCls=SubmissionEvent&objId=1448126639&dlCls=HaplotypeSet&dlId=PA165980499&dlName=CYP2D6%20Cytochrome%20P450%20Nomenclature%20DB%20Haplotype%20Set

Thanks

**Comment by markwoon** [comment]
The definition files are manually curated by CPIC.

For PharmCAT, we translate the manually curated files into a format that can easily be parsed.  These generated definition files are located in the /generatedFiles directory.

**Comment by gpcr** [comment]
my point was.... For many genes available definition files were not available? For example to explore CYP2D6 or other CYP genes to use to identify the haplotypes using PharmgKB  allele translation table?

**Comment by markwoon** [comment]
This repo contains CPIC-only data.  Support for more genes will be coming
in the future as this is a work in progress.

PharmGKB has not converted over to the format required to support PharmCAT.

On Aug 8, 2016 9:10 AM, "gpcr" <notifications@github.com> wrote:

my point was.... For many genes available definition files were not
available? For example to explore CYP2D6 or other CYP genes to use to
identify the haplotypes using PharmgKB allele translation table?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/PharmGKB/cpic-data/issues/1#issuecomment-238121671>,
or mute
the thread
